# Generated by Django 3.2.8 on 2021-10-21 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 43, 26, 418702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 43, 26, 402300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 43, 26, 418702, tzinfo=utc)),
        ),
    ]
